<a href="https://colab.research.google.com/github/HerveMignot/AdventOfCode/blob/main/2021/Advent_of_Code_2021_day_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Advent of Code 2021 day 4 🎄

## Input

Quite long text cell, hidden

In [1]:
INPUT = """42,44,71,26,70,92,77,45,6,18,79,54,31,34,64,32,16,55,81,11,90,10,21,87,0,84,8,23,1,12,60,20,57,68,61,82,49,59,22,2,63,33,50,39,28,30,88,41,69,72,98,73,7,65,53,35,96,67,36,4,51,75,24,86,97,85,66,29,74,40,93,58,9,62,95,91,80,99,14,19,43,37,27,56,94,25,83,48,17,38,78,15,52,76,5,13,46,89,47,3

48 69 68 49 13
25 14 30 74 89
16 38 19 24 29
56 97 50 65 79
57 52  5 27 76

65 69 73 60 66
79 23 95 32 56
36 51 26  1 28
76  9  3 71 77
41 15 61 68 14

77 86 11 96 50
64 35 76 14  5
31 20 53 84 66
83 40  1 28 79
15 74 92 65 39

20 55 65 13 48
 1  3 98 78 29
58 45 39 18 34
43 26 83 33 50
84 15 62 71 88

 0 10  3 19 47
51 43 62 11 70
38 59 56 81 55
77 36 39 91 74
23 14 67 12 80

36 18 47 14 60
33 96 84 44 72
 1 37 74 93 80
50 95 59 90 27
63 53 65 41 78

31  4 85 55 74
65 73  2 52  0
99 82 83 25 81
70 75 90 91 89
44 15 53 67 39

11 39 36 37 32
84 19 58 34 48
 3 69 81 41 59
86  2 56 47 90
31 12 17 14 40

28 13 34 45 37
83 55 61 80 92
77 33 44 40 31
54 25 71 56 93
60 70 20 65  9

82 60 11 40 90
 0 75 86 55 58
24  9 72 89 56
54 16 22 70 57
64 39 31 33  5

56 24 42 76 29
 0 60 12 84 73
72 81 99 15 70
88 90 80 26 65
61 47 19  7 17

28 64 80  3 41
32  0 22 18 97
87 94  1 52 83
37 29 14  5 82
73 58 56 88 49

70 23 43 81 66
27 14 38  8 13
26 17  6 67 83
91 96 37 39 18
19 25 77 98 53

33 12 42  4 44
88 99 61 27 43
68 13 38 57 87
59 20  2 90 40
80 64 77 94 21

47 29 58 72 24
26 66 42 68 36
34 80 76 94 59
61 41 64 44 50
 2 28 20  9 17

88  3 36 39  0
83 54 86  9 92
14 82 34 62 73
63 95 78 23 55
24 41 47  2 58

78 85 93 38 30
41  0 29 39 40
28 76 98 60 96
26 94 35  1 82
66 56 31 64 45

30 15 12 44 24
32 49 99 76  8
64 56 43 42 19
62 83 33 48 54
89 74 72  3 91

76 48 51 11 16
67 78 71 62 58
56 29 74  5 17
 9 81 65 12 39
19 24  1 13 30

72 96 63  4 62
71 47  9 56 90
12 86 52 10  3
49 83 73  7 87
85 64 48 81 32

28 72 38 47 63
37 14 13 51 27
 8 82 46 86 55
22 18 59 81 10
77 21 58 24 25

92 49 67 19 85
45 50 41 79 84
 4  0 75 17 53
91 23 28 82  6
60 37 18 13 69

 1 27 74 89  4
29  9 78 48 54
10 38 13 40 49
71 73 79 77 17
25 22 91 20  2

94 40 75 63 10
89 81 32 72 73
 8 65 68 62 58
76 97 57 34 66
 0 82 14 90 11

30 89 82 29 85
41 78 91 73 14
66 98 21 23 16
63 65 99 10 58
67 51 17 11 19

37 74 52 31 28
48 14 13 72 59
45 30 46  7  9
89 77 16 33 81
62  4 15  5 96

72 63 77 57 86
 8 65 11 44 69
78 52 14 84 80
36 42 30 59 33
46 10 92 19 26

13 65 92  1  5
71 54 28 33 98
42 94 30 35 78
57 85 25 60  7
43 80 48 97 27

29 64 61 99 74
94 68 72 36 51
11 83 21 96 86
56 53 25 48 92
60 15 19 50 76

12 61 89 99 30
84 50 34 74 55
26 72 36 86  3
 4 79  6  8 40
 5 83 82 66 44

40 93 61 20 50
90  7 60 38 16
22 52  3 92  5
32  0 57 58 30
68 28 81 46 54

86 72 55 48 24
21  3 25 22 20
16 64 97 77 68
66  2  9 47 30
36 87 67 23  0

18 54 51 38 44
73 50 68 59 61
45  0  5 80 19
79 65 66 30 15
26 74 23 99 95

75  9 34 74 86
53 14 25 61 31
17 60 10 32 93
47 33  0 77 68
38 45  4 55 39

32 81 21 11 31
30 56  3 25 18
80 96 20 65 71
41 67 22 97 10
93 68 17 13  1

54 42 23  8 83
87 63 36 95 81
40 14 13  6 18
44 16 89 59 69
17 10 73 76  5

36 69  2 13 74
17  7  9 42 54
79 21  5 19 66
68 22  4 85 25
63 23 10 75 87

27 61 41 78  4
77 76 82 85 17
74  0 54 63 34
 6 56  1 16 89
 8 12 36 59 81

37 22  9 36 19
79 61 78 96 91
41 11 42  8 24
85 84 35 47 31
50 16 62 53 21

93 61 14 78 75
51 88  3 54 37
57 36 23 77 91
72 47 39 65 35
 2 58 86 81 27

 0 34 82 13 53
 5 88 42 11 45
26 81 28 46 24
67 71 95  6  9
69 97 41 15  7

92 25 31 62 35
83 72 54 61 41
28 51 45 79  3
16 38 52 58  2
37  7 36 21 22

92 33 21 47 89
14 40 23 82 59
42 73  4 94 72
67 63 16  8 75
70 43 48 81 13

63 99 85 39 15
58 68 62 50 24
25 60 26  5 94
 8 53 75 46 61
66  3 16 47 42

21 89 33 61 12
36 83 76 80 24
93 95  4  0  7
91 43 17 14 64
84 71 45 44  5

23 74 19 40 42
83 75 15 12 21
 4 11 90 51 53
 1 77 54 62 82
28  5 46 52 79

73 60 22  3 71
53 67 30 58 15
59 89 40 21 31
13 42 84 97 10
81  6 70 88 52

91 26 38 80 79
46 24 66 53 93
25  2 58 59 63
65 78 36  7  1
83 72 50 39 21

31 22 32 36 79
97 60 62 43 96
 7 15 71 89 87
76 95 10 19 48
68 69 29 24 56

25 40 47 50 31
15 13 45 66 30
12 67 95  3 48
43 61 60 75 59
16 69 98  6 88

10 80 15 17 23
87 52 56 51 22
43 58 96 63 27
29 13 33 66 25
16 97 88 90 77

 5 11 90  8 18
51 42 73 25 85
69 94 79 53 32
72 23 57 15  3
78 28 47 37 35

80 81 44 53 14
36 71 35 83 30
94 40  2 99 97
16 48 85 76 20
56 25 89 88 39

34 54  9 36 44
14 19  0 64 40
25 78 74 18 13
82 10  6 92 95
84  8 75 98 45

95  8 27 29 89
33 79 88 59 24
 4 28 35 72 97
22 77 85 94 76
46 43 68 65 67

42 13  3 20 43
12 98 31 69  4
56 67 25 89 71
16 29 33  1 36
27 80  0 47  5

62 66 86 63 70
44 27  5 78 85
49 40 58 61 89
37 43 36 68 28
22  7 35 52 57

73 62 90 75 81
31 94 77 44 14
18  9 10 93 17
89 39 63 66 53
42 88 59 36  2

54 52 76 79 61
95 39  3 41 63
74 97 38  0 15
 6 23 11 10 83
46 67 96 77 29

 0 76  9 84 52
45 27 29 56 85
89 63 77 49 65
 4 13 78 33 37
64  7  1 94 12

16 32 78 73 90
 2 48 57 75 23
95 27 33 12 51
69 26 17 42 61
67 89 74 44 15

47 90  5 76 96
71 24  9 69 16
64 23 98 66 81
29 34 63 72 22
41 17 45 87 57

48 45 87 14  1
86 28  6 62 46
27 92 11 49 94
 0 90 10 70 20
 2 59 88 96 33

16 29 68  4 82
56 67  2 69 25
94 47 61 51 32
70 31 21 43 42
76 60 17 59 92

18  6 87 56 61
89 53  5 47 69
93 57 78 41 82
27 24 51 99 29
42 74 28 75 97

21 62 60 86 85
24 35  1 29  2
89 15 72 70 39
99 79 87 93 34
53 71 10 20 50

76 55 18 28 33
37 14 64  7  0
13 60 54 62  5
61  3 99 56 10
30 86 47 24 39

24 96 18 55 52
79 73 91 14 88
42 37 12 64 21
45 51 33 34  3
 8 77 47 40 16

55 54 98 85 97
80 21 27 15 36
 1 26  7 70 44
48 25 59  0 38
 5 58 18  3 12

76 78 79 92 88
 7 80 57 68 28
27 16  8 10 62
32 98 64 60 39
52  4 85 48 35

94 64 19 67 12
49 61 77 89 31
80 11 18 26 83
21 76 66 85 91
60 88 28 86 69

88 27 52 28 89
 3  5 15 78 97
79 34  7 42 80
14 83 90 68 65
35 13 58 71 17

90 10  0 30 69
64 75 61 62 97
 3 29 40 58 57
98 48  5 37 23
70 12  6 36  7

27 87 59 84 83
19 91 24 32 78
62 14 58 18 68
37  1 99 44 94
71 23 54  8 74

12 78  7 55 59
81 87 69 49 22
79 99 84 58 65
40 42 85 74 91
61 39 51 88 36

 2  9 62 76 11
87 36 72 80 96
28 16  7 17 39
68 33  5 71 92
41 22 70  4 52

49  1 23 37 60
72 79  2 40 13
31 47 59 48 33
96 80 62  3 12
34 89 75 18 95

34 72  3 78 60
57 51 47 26  7
 2 50 82  4 56
81 95 22 42 73
25 37 97 65  6

86 23 17 39 53
 6 49 66 32 30
71 40 64 11  8
82 60 18 13 68
12  7 42 52 72

16  0 88 84 98
42 92 19 89  2
51 26  1 33 10
40 87 32 17 27
 7 68 35 50 11

39 52 56 23 75
66 64 26 10 53
46 25 60 48 28
61 27 98 40 59
65 95 85 13 62

74 32 72 43 23
26 90 83 68 82
48 60 39 17 54
51 36 37 85 88
99 81 69 50 93

16 71  3 29 81
18 97 17 20 48
95 38 61 87 98
52 76  8 42 36
45  4 78 55 89

64 18 54 39 77
36 66 98 88 38
49 50 74 69 65
71  3 93 34 82
23 26 92 15 33

18 99 45 69  8
32 75 47  2 91
41 55 90  5  3
93 11 84 78 56
80 57 51 50 74

90  0 19 53 11
69 50 47 16 26
 5 32 73 51 14
84 37 34  7 56
68 10 74 29 62

42 80  7 72 35
 1 50 15  0 49
43 19 41 26 48
65  2 36 17 20
85 32  5 75 30

 8 80 72  1 81
90 69 48 36 23
55 16 35 41  5
71 12 59 29 79
60 92 53 73 96

45 55 75 77  6
 1 91 76  5 39
54 65 61 34  8
27 59 47 85 44
66 29 36 80 60

82 75 32 29 14
41 21 20 68 89
80 64 56 33 31
13 12 55 81  7
36 78  4 24 50

55 28 90 35 22
77 92 56 16 47
48  4 67 95 37
63 80 36 12 44
88 58 10 68 84

 7 88 53 55 60
81 99 91 28 70
75  8  0 40 84
17 24 30 71 56
78 20 83 29 74

10 16 11  5 38
72 77 37 68 81
78 13 45 89 46
90 49 18 53 42
71  0 28 26 75

36 73 23 44  7
 1 96 17 11 42
77 54 68 80 79
85 56 28 58 52
57  2 43 18 61

 9 18 29 44 61
13 80 57 95 47
 2 15 72 50 65
77 12 42 64 36
49 67 31  6 90

99 74  9 64 59
17 87 86  5 28
44 41 82 53 45
95 51 98 50 94
22 37 46 25  4

46 54 82 17 77
88 63 50 65 64
 5 19 39 21 11
57 58 20  6 40
99 37 66 70 95

30 68 11 29 13
 1 69  0  9 93
33 57 23 50 71
 8 77  6 25 45
34 12 60  7 28

91 53 88 47 40
77 92 87 37 84
89 95 78 21 39
65 20 54 94 85
45 74 30 49 11

 3 58 90 93 96
53 66 24 43 32
62 84 19 82 22
13 89 20 97  1
15 91 51 68 49
"""

In [9]:
TESTS = """7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1

22 13 17 11  0
 8  2 23  4 24
21  9 14 16  7
 6 10  3 18  5
 1 12 20 15 19

 3 15  0  2 22
 9 18 13 17  5
19  8  7 25 23
20 11 10 24  4
14 21 16 12  6

14 21 17 24  4
10 16 15  9 19
18  8 23 26 20
22 11 13  6  5
 2  0 12  3  7
 """

## Code

In [6]:
import io

import numpy as np

def read_inputs(input: str):
  with io.StringIO(input) as f:
    lines = f.readlines()

  draws = list(map(int, lines[0][:-1].split(',')))

  boards = list()
  for start in range(2, len(lines), 6):
    boards.append(np.array([list(map(int, l[:-1].split())) for l in lines[start:start + 5]]))
  
  return draws, boards

In [7]:
draws, boards = read_inputs(INPUT)

In [10]:
test_draws, test_boards = read_inputs(TESTS)

## Part 1

In [31]:
def check_draw(board, check, value):
  """Mark on the check array the value if it is on the board"""
  loc = np.argwhere(board == value) 
  if loc.shape[0] == 0:
    return check
  else:
    check[loc[0][0], loc[0][1]] = 1
    return check

def has_row_or_col_complete(check, size=5):
  """Test if the check array has one column or row completed"""
  return (check.sum(axis=0).max() == size) or (check.sum(axis=1).max() == size)

### Implement on tests

In [16]:
checks = [np.zeros(board.shape) for board in test_boards]

score = None
found = False

for ball in test_draws:
  for board, check in zip(test_boards, checks):
    if has_row_or_col_complete(check_draw(board, check, ball)):
      found = True
      break
  
  if found:
    score = (board.sum() - np.multiply(board, check).sum()) * ball
    break

if score:
  print('Score:', score)
  print(ball, test_draws)
  print(board)
  print(check)
else:
  print('No grid finished')

Score: 4512.0
24 [7, 4, 9, 5, 11, 17, 23, 2, 0, 14, 21, 24, 10, 16, 13, 6, 15, 25, 12, 22, 18, 20, 8, 19, 3, 26, 1]
[[14 21 17 24  4]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3  7]]
[[1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1.]
 [1. 1. 0. 0. 1.]]


### Puzzle input

In [4]:
checks = [np.zeros(board.shape) for board in boards]

score = None
found = False

for ball in draws:
  for board, check in zip(boards, checks):
    if has_row_or_col_complete(check_draw(board, check, ball)):
      found = True
      break
  
  if found:
    score = (board.sum() - np.multiply(board, check).sum()) * ball
    break

if score:
  print('Score:', score)
  print(board)
  print(check)
else:
  print('No grid finished')


Score: 16674.0
[[32 81 21 11 31]
 [30 56  3 25 18]
 [80 96 20 65 71]
 [41 67 22 97 10]
 [93 68 17 13  1]]
[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


## Part 2

### Implement on tests

In [26]:
checks = [np.zeros(board.shape) for board in test_boards]

score = None
complete = set()

for ball in test_draws:
  for number, (board, check) in enumerate(zip(test_boards, checks)):
    if has_row_or_col_complete(check_draw(board, check, ball)):
      complete.add(number)
      if len(complete) == len(test_boards):
        score = (board.sum() - np.multiply(board, check).sum()) * ball
        break
  if score:
    break

if score:
  print('Score:', score)
  print(ball, test_draws)
  print(board)
  print(check)
else:
  print('No grid finished')

Score: 1924.0
13 [7, 4, 9, 5, 11, 17, 23, 2, 0, 14, 21, 24, 10, 16, 13, 6, 15, 25, 12, 22, 18, 20, 8, 19, 3, 26, 1]
[[ 3 15  0  2 22]
 [ 9 18 13 17  5]
 [19  8  7 25 23]
 [20 11 10 24  4]
 [14 21 16 12  6]]
[[0. 0. 1. 1. 0.]
 [1. 0. 1. 1. 1.]
 [0. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1.]
 [1. 1. 1. 0. 0.]]


### Puzzle input

In [28]:
checks = [np.zeros(board.shape) for board in boards]

score = None
complete = set()

for ball in draws:
  for number, (board, check) in enumerate(zip(boards, checks)):
    if has_row_or_col_complete(check_draw(board, check, ball)):
      complete.add(number)
      if len(complete) == len(boards):
        score = (board.sum() - np.multiply(board, check).sum()) * ball
        break
  if score:
    break

if score:
  print('Score:', score)
  print(ball)
  print(board)
  print(check)
else:
  print('No grid finished')

Score: 7075.0
25
[[ 1 27 74 89  4]
 [29  9 78 48 54]
 [10 38 13 40 49]
 [71 73 79 77 17]
 [25 22 91 20  2]]
[[1. 1. 1. 0. 1.]
 [1. 1. 0. 0. 1.]
 [1. 0. 0. 1. 1.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]
